function english() {
  const content = [
    "HI I'M FRANCISCO, FULL STACK WEB DEVELOPER",
    "WELCOME TO MY PORTAFOLIO",
    "DO YOU WANT TO KNOW MORE ABOUT ME?, SCROLL AND YOU WILL SEE THE MAGIC",
    "ABOUT ME",
    "MY PASSION FOR COMPUTERS STARTED AT 12 YEARS OLD, AT 18 IT WAS THE FIRST TIME I OBSERVED PROGRAMMING IN THIS CASE IT WAS IN C++ IN UNIVERSITY WHAT IGNITED MY PASSION, SINCE 2013 I PRACTICE PROGRAMMING LOGIC AND TIME LATER I DECIDED TO SPECIALIZE IN WEB TECHNOLOGIES, THEREFORE I STARTED LEARNING HTML, CSS, JAVASCRIPT AND PHP, CURRENTLY WORKING IN THE AREA SINCE 2016",
    "DO YOU WANT TO KNOW WHAT TECHNOLOGIES I CURRENTLY USE?, USE THE SCROLL",
    "WHAT TECHNOLOGIES, FRAMEWORKS AND CMS DO I CURRENTLY USE?",
    "WHAT PROJECTS HAVE YOU DONE?, USE THE SCROLL",
    "MY PROJECTS",
    "CHECK MORE PROJECTS IN MY GITHUB",
    "SCROLL AND YOU WILL SEE MY CURRENTLY TAKEN COURSES",
    "MY LAST COURSES",
    "DOWNLOAD ALL CERTIFICATES",
    "THIS IS ALL, BUT IF YOU SCROLL YOU WILL HAVE A SURPRISE",
    "HAPPY DAY :)",
  ];
  return content;
}

function spanish() {
  const content = [
    "HOLA SOY FRANCISCO, DESARROLLADOR WEB FULL STACK",
    "BIENVENIDO A MI PORTAFOLIO",
    "¿QUIERES SABER MÁS DE MÍ?, HAZ SCROLL Y VERÁS LA MAGIA",
    "SOBRE MÍ",
    "MI PASIÓN POR LAS COMPUTADORAS COMENZÓ A LOS 12 AÑOS, A LOS 18 FUE LA PRIMERA VEZ QUE OBSERVÉ LA PROGRAMACIÓN EN ESTE CASO FUE EN C++ EN LA UNIVERSIDAD LO QUE ENCIENDO MI PASIÓN, DESDE EL 2013 PRACTICO LA LÓGICA DE PROGRAMACIÓN Y TIEMPO DESPUÉS DECIDI ESPECIALIZARME EN TECNOLOGÍAS WEB , POR LO TANTO COMENCE APRENDIENDO HTML, CSS, JAVASCRIPT Y PHP, ACTUALMENTE TRABAJO EN EL AREA DESDE 2016",
    "¿QUIERES SABER QUÉ TECNOLOGÍAS UTILIZO ACTUALMENTE?, HAZ SCROLL",
    "¿QUÉ TECNOLOGÍAS, FRAMEWORKS Y CMS UTILIZO ACTUALMENTE?",
    "¿QUÉ PROYECTOS HAS REALIZADO?, HAZ SCROLL",
    "MIS PROYECTOS",
    "REVISAR MAS PROYECTOS EN MI GITHUB",
    "DESLIZA Y VERÁS MIS CURSOS TOMADOS ACTUALMENTE",
    "MIS ULTIMOS CURSOS",
    "DESCARGAR TODOS LOS CERTIFICADOS",
    "ESTO ES TODO, PERO SI DESPLAZAS TE LLEVARAS UNA SORPRESA",
    "FELIZ DIA :)",
  ];
  return content;
}

module.exports = { english, spanish };
